# This is a basic workflow to help you get started with Actions for cli
name: Dynamic Specifications

# Controls when the workflow will run
on:  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     clirelease:
        # target_release input from users
        description: Topaz CLI release
        default: ""
        required: true
     targetbranch:
        # target_branch input from users
        description: GIT BRANCH FOR CHECKOUTS
        default: ""
        required: true
     VM:
        # target_host input from the user.
        description: THE VM TO EXECUTE THE TESTS
        default: ""
        required: true
     clipath:
        # Workspcae location of the customer input from the user.
        description: CLI path
        default: ""
        required: true
     repository:
        # repository server input from the user.
        description: repository
        default: ""
        required: true   
     host-ID:
        # host-ID input from the user.
        description: Host-ID
        default: ""
        required: true
    host-password:
      #host-password input from the user.
      description: Host-Password
      default: ""
      required: true
       ComparePro_CLI :
        # specification input from the user.
        description: specification for ComparePro
        default: ""
    ConverterProSpec1_CLI :
        # specification input from the user.
        description: specification for ConverterPro
        default: ""
    ExecutionSuiteCLI :
        # specification input from the user.
        description: specification for ExecutionSuiteCLI
        default: ""
    EMPROJACT_CLI :
        # specification input from the user.
        description: specification for EMPROJACT_CLI
        default: ""
    Mvs2Db2Extract_Loadtest :
        # specification input from the user.
        description: specification for Mvs2Db2extract_LoadTest
        default: ""
    RdxLoad_FilesAndTables_New :
        # specification input from the user.
        description: specification for RdxLoad_FilesAndTables_New
        default: ""
    ConverterProSpec1_CLI convert EMPPROJACT_CLI extract Mvs2Db2Extract_LoadTest extract :
        # specification input from the user.
        description: specification for ConverterProSpec1_CLI convert EMPPROJACT_CLI extract Mvs2Db2Extract_LoadTest extract
        default: ""
  execution-context:
        # execution-context server input from the user.
        description: execution-context
        default: ""
        required: true
  specification-type-ComparePro:
      # specification type input from the user.
        description: specification type for ComparePro
        default: ""
  specification-type-ConverterPro:
      # specification type input from the user.
        description: specification type for ConverterPro
        default: ""
  specification-type-ExecutionSuiteCLI:
      # specification type input from the user.
        description: specification type for ExecutionSuiteCLI
        default: ""
   
  specification-type-EMPROJACT_CLI1 :
      # specification type input from the user.
        description: specification type for EMPROJACT_CLI 
        default: ""
  specification-type-EMPROJACT_CLI2 :
      # specification type input from the user.
        description: specification type for EMPROJACT_CLI 
        default: ""
  specification-type-Mvs2Db2Extract_Loadtest:
      # specification type input from the user.
        description: specification type for Mvs2Db2Extract_Loadtest
        default: ""
  specification-type-RdxLoad_FilesAndTables_New:
      # specification type input from the user.
        description: specification type for RdxLoad_FilesAndTables_New
        default: ""    
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, TEDCLI]
    env:
     HCI_PASSWORD: ${{ secrets.HCI_PASSWORD }}
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
    # Runs a single command using the runners shell
      - name: ComparePro
        run: ${{inputs.clipath}}\TedCLI.bat -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.ComparePro_CLI}}" -execution-context="${{inputs.execution-context}}" -specification-type="${{inputs.specification-type-ComparePro}}" -rr=EXRVRESULTS 
     
     # Runs a single command using the runners shell
      - name: ConverterPro
        run: ${{inputs.clipath}}\TedCLI.bat -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.ConverterProSpec1_CLI}}"  -specification-type="${{inputs.specification-type-ConverterPro}}" 
     
     
      # Runs a single command using the runners shell
      - name: ExecutionSuite
        run: ${{inputs.clipath}}\TedCLI.bat -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.ExecutionSuiteCLI}}"  -specification-type="${{inputs.specification-type-ExecutionSuiteCLI}}" 
     
     # Runs a single command using the runners shell
      - name: EMPPROJACT_Extract
        run: ${{inputs.clipath}}\TedCLI.bat -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.EMPROJACT_CLI}}"  -specification-type="${{inputs.specification-type-EMPROJACT_CLI1}}"
      
     # Runs a single command using the runners shell
      - name: EMPPROJACT_Load
        run: ${{inputs.clipath}}\TedCLI.bat -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.EMPROJACT_CLI}}"  -specification-type="${{inputs.specification-type-EMPROJACT_CLI2}}"
      
    # Runs a single command using the runners shell
      - name: Mvs2Db2Extract
        run: ${{inputs.clipath}}\TedCLI.bat  -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.Mvs2Db2Extract_Loadtest}}"  -specification-type="${{inputs.specification-type-Mvs2Db2Extract_Loadtest}}" -hid="${{inputs.host-ID}}" -hpw="${{inputs.host-password}}" -execution-timeout=60 
     
   # Runs a single command using the runners shell
      - name: RdxLoad_FilesAndTables
        run: ${{inputs.clipath}}\TedCLI.bat  -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.RdxLoad_FilesAndTables_New}}" -specification-type="${{inputs.specification-type-RdxLoad_FilesAndTables_New}}" -execution-timeout=60 
   
    # Runs a single command using the runners shell
      - name: ConverterProSpec1
        run: ${{inputs.clipath}}\TedCLI.bat  -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification-list="${{inputs. ConverterProSpec1_CLI convert EMPPROJACT_CLI extract Mvs2Db2Extract_LoadTest extract}}" -hid="${{inputs.host-ID}}" -hpw="${{inputs.host-password}}" -exit-on-failure=true 
    
