# This is a basic workflow to help you get started with Actions for cli
name: ComparePro

# Controls when the workflow will run
on:  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      clirelease:
        # target_release input from users
        description: Topaz CLI release
        default: ""
        required: true
      targetbranch:
        # target_branch input from users
        description: GIT BRANCH FOR CHECKOUTS
        default: ""
        required: true
         Git_branch:
        # target_host input from the user.
        description: THE VM TO EXECUTE THE TESTS
        default: ""
        required: true
        VM:
        # Workspace location of the customer input from the user.
        description: CLI path
        default: ""
        required: true
       clipath:
        # repository server input from the user.
        description: repository
        default: ""
        required: true        
      repository:
        # specification input from the user.
        description:Specification
        default: ""
        required: true
      Specification:
        # specification type input from the user.
        description: Specification-type
        default: ""
        required: true
        Specification_type:
         # execution-context input from the user.
        description: execution-context
        default: ""
        required: true
        execution-context:
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, TEDCLI]
    env:
     HCI_PASSWORD: ${{ secrets.HCI_PASSWORD }}
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true    
          
      # Runs a single command using the runners shell
      - name: ComparePro
        run: ${{inputs.clipath}}\\TedCLI.bat -cmd=execute -repository "${{inputs.repository}}" -specification="${{inputs.specification}}" -execution-context="${{inputs.execution-context}}" -specification-type="${{inputs.specification-type}}" -rr=EXRVRESULTS 
     
    
