# This is a basic workflow to help you get started with Actions for cli
name: SEND MAIL

# Controls when the workflow will run
on:  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send_mail:
    # The type of runner that the job will run on
    runs-on: [self-hosted, TEDCLI]
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Runs a single command using the runners shell
              - name: Send some mail
                uses: MeghGanguly/topaz-for-enterprise-data-github-actions@main
                with:    
                  server_address: smtp.gmail.com
                  port: 465      
                  subject: Github TEDCLI
                  body: Job completed  
                  to: vijay_sancheti@bmc.com, megha_ganguly@bmc.com
                  from: imf@bmc.com
