# This is a basic workflow to help you get started with Actions for cli
name: BMC AMI DEVx Data Studio

# Controls when the workflow will run
on:  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      targethost:
        # target_host input from users
        description: Target Host
        default: ""
        required: true
        
      clipath:
        # Workspcae location of the customer input from the user.
        description: CLI Path
        default: ""
        required: true
      repository:
        # repository server input from the user.
        description: repository
        default: ""
        required: true        
      specification:
        # specification input from the user.
        description: specification
        default: ""
        required: true
      execution-context:
        # execution-context server input from the user.
        description: execution-context
        default: ""
        required: true
      specification-type:
      # specification type input from the user.
        description: specification type
        default: ""
        required: true
      userId:
        # repository server input from the user.
        description: HCI User ID
        default: ""
      Password:
      #Password input from the user.
      description: Password
      default: ""

        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, TEDCLI]
    env:
     HCI_PASSWORD: ${{ secrets.HCI_PASSWORD }}
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Runs a single command using the runners shell
      - name: TED_CLI
        run: ${{inputs.clipath}}\TedCLI.bat  -execution-context="${{inputs.execution-context}}" -cmd=execute -repository="${{inputs.repository}}" -specification="${{inputs.specification}}"  -specification-type="${{inputs.specification-type}}" -hid="${{inputs.userId}}" -hpw="${{inputs.Password}}" -execution-timeout=60 
     
   
